using System.Text;

namespace BeamSharp.Serialization.Generator;

/// <summary>Writes the C# source for a context and its converters.</summary>
internal static class Emitter
{
    private const string N = "global::BeamSharp.Serialization.";
    private const string T = "global::BeamSharp.Terms.";
    private const string G = N + "ErlGenerated.";
    private const string C = N + "Converters.";

    public static string Emit(ContextModel context)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        // Generated code assigns deserialized values into whatever the member declared; the runtime
        // check lives in the converter, so the compiler's nullability opinion here is noise.
        sb.AppendLine("#pragma warning disable CS8600, CS8601, CS8603, CS8604, CS8619, CS8625");
        sb.AppendLine();

        var indent = 0;
        if (context.Namespace is not null)
        {
            sb.AppendLine($"namespace {context.Namespace}");
            sb.AppendLine("{");
            indent = 1;
        }

        var pad = new string(' ', indent * 4);

        sb.AppendLine($"{pad}partial class {context.ClassName}");
        sb.AppendLine($"{pad}{{");
        sb.AppendLine($"{pad}    /// <summary>A shared instance using the default options.</summary>");
        sb.AppendLine($"{pad}    public static {context.ClassName} Default {{ get; }} = new {context.ClassName}();");
        sb.AppendLine();
        sb.AppendLine($"{pad}    protected override {N}ErlConverterFactory CreateFactory() => new GeneratedFactory();");
        sb.AppendLine();

        EmitFactory(sb, pad + "    ", context);

        foreach (var type in context.Types)
        {
            sb.AppendLine();
            EmitConverter(sb, pad + "    ", type);
        }

        sb.AppendLine($"{pad}}}");

        if (context.Namespace is not null) sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitFactory(StringBuilder sb, string pad, ContextModel context)
    {
        sb.AppendLine($"{pad}private sealed class GeneratedFactory : {N}ErlConverterFactory");
        sb.AppendLine($"{pad}{{");
        sb.AppendLine($"{pad}    public override bool CanConvert(global::System.Type type)");

        var handled = context.Types.Select(t => t.TypeName)
            .Concat(context.Auxiliaries.Select(a => a.TypeName))
            .ToArray();

        if (handled.Length == 0)
        {
            sb.AppendLine($"{pad}        => false;");
        }
        else
        {
            var conditions = handled.Select(t => $"type == typeof({t})").ToArray();
            sb.AppendLine($"{pad}        => {string.Join("\n" + pad + "        || ", conditions)};");
        }

        sb.AppendLine();
        sb.AppendLine($"{pad}    public override {N}ErlConverter CreateConverter(");
        sb.AppendLine($"{pad}        global::System.Type type, {N}ErlSerializerOptions options)");
        sb.AppendLine($"{pad}    {{");

        foreach (var type in context.Types)
        {
            sb.AppendLine($"{pad}        if (type == typeof({type.TypeName})) return new {type.SafeName}Converter(options);");
        }

        // Member types reached from the declared ones. Writing the instantiation out is the whole
        // point: MakeGenericType would leave the native code for it unreachable under AOT.
        foreach (var aux in context.Auxiliaries)
        {
            sb.AppendLine($"{pad}        if (type == typeof({aux.TypeName}))");
            sb.AppendLine($"{pad}            return {AuxiliaryExpression(aux, pad + "            ")};");
        }

        sb.AppendLine($"{pad}        throw new {N}ErlSerializationException(");
        sb.AppendLine($"{pad}            \"no converter was generated for \" + type);");
        sb.AppendLine($"{pad}    }}");
        sb.AppendLine($"{pad}}}");
    }

    private static string AuxiliaryExpression(AuxiliaryModel aux, string pad)
    {
        switch (aux.Kind)
        {
            case AuxiliaryKind.Collection:
                return $"new {C}ErlCollectionConverter<{aux.TypeName}, {aux.Arg1}>()";

            case AuxiliaryKind.Dictionary:
                return $"new {C}ErlDictionaryConverter<{aux.TypeName}, {aux.Arg1}, {aux.Arg2}>()";

            case AuxiliaryKind.Nullable:
                return $"new {C}ErlNullableConverter<{aux.Arg1}>(options)";

            case AuxiliaryKind.Enum:
            {
                var tuple = $"global::System.ValueTuple<{aux.TypeName}, string, string?>";
                var members = aux.EnumMembers
                    .Select(m => $"new {tuple}({aux.TypeName}.{m.ClrName}, {Quote(m.ClrName)}, " +
                                 $"{(m.ExplicitName is null ? "null" : Quote(m.ExplicitName))})")
                    .ToArray();

                var sb = new StringBuilder();
                sb.Append($"new {C}ErlEnumConverter<{aux.TypeName}>(options, new {tuple}[]");
                sb.Append("\n").Append(pad).Append("{");
                foreach (var member in members) sb.Append("\n").Append(pad).Append("    ").Append(member).Append(",");
                sb.Append("\n").Append(pad).Append("})");
                return sb.ToString();
            }

            default:
                throw new global::System.InvalidOperationException($"unhandled auxiliary kind {aux.Kind}");
        }
    }

    private static void EmitConverter(StringBuilder sb, string pad, TypeModel type)
    {
        var members = type.Members.ToArray();
        var isStruct = type.Shape == TermShape.Struct;
        var isRecord = type.Shape == TermShape.Record;

        sb.AppendLine($"{pad}private sealed class {type.SafeName}Converter : {N}ErlConverter<{type.TypeName}>");
        sb.AppendLine($"{pad}{{");

        // --- fields
        sb.AppendLine($"{pad}    private readonly bool _includeFields;");
        if (isStruct)
            sb.AppendLine($"{pad}    private static readonly {T}ErlTerm _structKey = new {T}ErlAtom(\"__struct__\");");
        if (isStruct)
            sb.AppendLine($"{pad}    private static readonly {T}ErlTerm _structValue = new {T}ErlAtom(\"{type.StructModule}\");");
        if (isRecord)
            sb.AppendLine($"{pad}    private static readonly {T}ErlTerm _tag = new {T}ErlAtom(\"{type.RecordTag}\");");

        for (var i = 0; i < members.Length; i++)
        {
            if (!isRecord)
            {
                sb.AppendLine($"{pad}    private readonly {T}ErlTerm _key{i};");
                sb.AppendLine($"{pad}    private readonly {T}ErlTerm _atom{i};");
                sb.AppendLine($"{pad}    private readonly {T}ErlTerm _bin{i};");
            }

            if (members[i].ConverterTypeName is { } converterType)
                sb.AppendLine($"{pad}    private readonly {N}ErlConverter<{members[i].TypeName}> _conv{i} = new {converterType}();");
        }

        var needsTemplate = type.UsesParameterlessConstructor &&
                            members.Any(m => m.IsInitOnly && !IsConstructorBound(type, members, m));
        if (needsTemplate)
            sb.AppendLine($"{pad}    private static readonly {type.TypeName} _template = new {type.TypeName}();");

        // --- constructor
        sb.AppendLine();
        sb.AppendLine($"{pad}    public {type.SafeName}Converter({N}ErlSerializerOptions options)");
        sb.AppendLine($"{pad}    {{");
        sb.AppendLine($"{pad}        _includeFields = options.IncludeFields;");

        if (!isRecord)
        {
            sb.AppendLine($"{pad}        var names = new global::System.Collections.Generic.List<string>();");
            sb.AppendLine($"{pad}        var clrNames = new global::System.Collections.Generic.List<string>();");

            for (var i = 0; i < members.Length; i++)
            {
                var m = members[i];
                var explicitName = m.ExplicitName is null ? "null" : Quote(m.ExplicitName);
                sb.AppendLine($"{pad}        var n{i} = {G}Name(options, {Quote(m.ClrName)}, {explicitName});");
                sb.AppendLine($"{pad}        _key{i} = {G}Key(options, n{i}, {(isStruct ? "true" : "false")});");
                sb.AppendLine($"{pad}        _atom{i} = new {T}ErlAtom(n{i});");
                sb.AppendLine($"{pad}        _bin{i} = new {T}ErlBinary(n{i});");

                var guard = m.IsField ? "if (_includeFields) " : string.Empty;
                sb.AppendLine($"{pad}        {guard}{{ names.Add(n{i}); clrNames.Add({Quote(m.ClrName)}); }}");
            }

            sb.AppendLine($"{pad}        {G}EnsureDistinctKeys({Quote(ShortName(type.TypeName))}, names.ToArray(), clrNames.ToArray());");
        }

        sb.AppendLine($"{pad}    }}");

        // --- write
        sb.AppendLine();
        EmitWrite(sb, pad + "    ", type, members, isStruct, isRecord);

        // --- read
        sb.AppendLine();
        EmitRead(sb, pad + "    ", type, members, isRecord);

        sb.AppendLine($"{pad}}}");
    }

    private static void EmitWrite(StringBuilder sb, string pad, TypeModel type, MemberModel[] members,
        bool isStruct, bool isRecord)
    {
        sb.AppendLine($"{pad}public override {T}ErlTerm Write({type.TypeName} value, {N}ErlSerializerOptions options)");
        sb.AppendLine($"{pad}{{");
        sb.AppendLine($"{pad}    if (value is null) return options.NullAtom;");

        if (isRecord)
        {
            sb.AppendLine($"{pad}    var items = new global::System.Collections.Generic.List<{T}ErlTerm>();");
            sb.AppendLine($"{pad}    items.Add(_tag);");

            for (var i = 0; i < members.Length; i++)
            {
                var guard = members[i].IsField ? "if (_includeFields) " : string.Empty;
                sb.AppendLine($"{pad}    {guard}items.Add({WriteExpr(members[i], i, $"value.{members[i].ClrName}")});");
            }

            sb.AppendLine($"{pad}    return new {T}ErlTuple(items.ToArray());");
            sb.AppendLine($"{pad}}}");
            return;
        }

        sb.AppendLine($"{pad}    var entries = new global::System.Collections.Generic.List<" +
                      $"global::System.Collections.Generic.KeyValuePair<{T}ErlTerm, {T}ErlTerm>>({members.Length + 1});");

        if (isStruct)
            sb.AppendLine($"{pad}    entries.Add(new global::System.Collections.Generic.KeyValuePair<{T}ErlTerm, {T}ErlTerm>(_structKey, _structValue));");

        for (var i = 0; i < members.Length; i++)
        {
            var m = members[i];
            var open = m.IsField ? $"{pad}    if (_includeFields)" : null;
            if (open is not null)
            {
                sb.AppendLine(open);
                sb.AppendLine($"{pad}    {{");
            }

            var inner = open is null ? $"{pad}    " : $"{pad}        ";
            sb.AppendLine($"{inner}{{");
            sb.AppendLine($"{inner}    var v{i} = value.{m.ClrName};");

            // A null check on a non-nullable value type is dead code the compiler complains about.
            var addLine = $"entries.Add(new global::System.Collections.Generic.KeyValuePair<{T}ErlTerm, {T}ErlTerm>(_key{i}, {WriteExpr(m, i, $"v{i}")}));";
            if (m.CanBeNull)
            {
                sb.AppendLine($"{inner}    if (!(v{i} is null && options.IgnoreNullValues))");
                sb.AppendLine($"{inner}        {addLine}");
            }
            else
            {
                sb.AppendLine($"{inner}    {addLine}");
            }

            sb.AppendLine($"{inner}}}");

            if (open is not null) sb.AppendLine($"{pad}    }}");
        }

        sb.AppendLine($"{pad}    return new {T}ErlMap(entries);");
        sb.AppendLine($"{pad}}}");
    }

    private static void EmitRead(StringBuilder sb, string pad, TypeModel type, MemberModel[] members, bool isRecord)
    {
        var shortName = ShortName(type.TypeName);

        sb.AppendLine($"{pad}public override {type.TypeName} Read({T}ErlTerm term, {N}ErlSerializerOptions options)");
        sb.AppendLine($"{pad}{{");

        if (isRecord)
        {
            sb.AppendLine($"{pad}    var arity = 1;");
            foreach (var m in members)
                sb.AppendLine(m.IsField
                    ? $"{pad}    if (_includeFields) arity++;"
                    : $"{pad}    arity++;");

            sb.AppendLine($"{pad}    var tuple = {G}ExpectTuple(term, {Quote(type.RecordTag!)}, arity);");
            sb.AppendLine($"{pad}    var index = 1;");

            for (var i = 0; i < members.Length; i++)
            {
                var m = members[i];
                sb.AppendLine($"{pad}    {m.TypeName} v{i} = default({m.TypeName});");
                sb.AppendLine($"{pad}    bool has{i} = {(m.IsField ? "_includeFields" : "true")};");
                sb.AppendLine($"{pad}    if (has{i}) v{i} = {ReadExpr(m, i, "tuple[index++]")};");
            }
        }
        else
        {
            sb.AppendLine($"{pad}    var map = {G}ExpectMap(term, {Quote(shortName)});");

            for (var i = 0; i < members.Length; i++)
            {
                var m = members[i];
                sb.AppendLine($"{pad}    {m.TypeName} v{i} = {Fallback(type, members, m, i)};");
                sb.AppendLine($"{pad}    {T}ErlTerm t{i} = null!;");
                var guard = m.IsField ? "_includeFields && " : string.Empty;
                sb.AppendLine($"{pad}    bool has{i} = {guard}(map.TryGetValue(_atom{i}, out t{i}) || map.TryGetValue(_bin{i}, out t{i}));");
                sb.AppendLine($"{pad}    if (has{i}) v{i} = {ReadExpr(m, i, $"t{i}")};");
            }
        }

        EmitConstruction(sb, pad + "    ", type, members);

        sb.AppendLine($"{pad}}}");
    }

    private static void EmitConstruction(StringBuilder sb, string pad, TypeModel type, MemberModel[] members)
    {
        var binding = type.ConstructorBinding.ToArray();
        var arguments = new List<string>();

        for (var i = 0; i < binding.Length; i++)
        {
            var memberIndex = binding[i];
            arguments.Add(memberIndex >= 0
                ? $"has{memberIndex} ? v{memberIndex} : {type.ConstructorDefaults[i]}"
                : type.ConstructorDefaults[i]);
        }

        // Init-only members the constructor did not take can only be set in an object initializer.
        var initialisers = new List<string>();
        for (var i = 0; i < members.Length; i++)
        {
            var m = members[i];
            if (!m.IsInitOnly || IsConstructorBound(type, members, m)) continue;

            var fallback = type.UsesParameterlessConstructor
                ? $"_template.{m.ClrName}"
                : $"default({m.TypeName})";
            initialisers.Add($"{m.ClrName} = has{i} ? v{i} : {fallback}");
        }

        var construction = type.UsesParameterlessConstructor
            ? $"new {type.TypeName}()"
            : $"new {type.TypeName}({string.Join(", ", arguments)})";

        if (initialisers.Count > 0)
            construction += " { " + string.Join(", ", initialisers) + " }";

        sb.AppendLine($"{pad}var result = {construction};");

        // Everything else with a plain setter is assigned only when the key was actually present,
        // which is what preserves a member's own initialiser default.
        for (var i = 0; i < members.Length; i++)
        {
            var m = members[i];
            if (!m.IsSettable || m.IsInitOnly || IsConstructorBound(type, members, m)) continue;
            sb.AppendLine($"{pad}if (has{i}) result.{m.ClrName} = v{i};");
        }

        sb.AppendLine($"{pad}return result;");
    }

    private static bool IsConstructorBound(TypeModel type, MemberModel[] members, MemberModel member)
    {
        if (type.UsesParameterlessConstructor) return false;
        var index = Array.IndexOf(members, member);
        return type.ConstructorBinding.Any(b => b == index);
    }

    private static string Fallback(TypeModel type, MemberModel[] members, MemberModel member, int index)
    {
        if (type.UsesParameterlessConstructor) return $"default({member.TypeName})";

        var binding = type.ConstructorBinding.ToArray();
        for (var i = 0; i < binding.Length; i++)
            if (binding[i] == index)
                return type.ConstructorDefaults[i];

        return $"default({member.TypeName})";
    }

    private static string WriteExpr(MemberModel member, int index, string value) =>
        member.AsAtom ? $"{G}WriteAtomString({value}, options)"
        : member.ConverterTypeName is not null ? $"{G}WriteVia(_conv{index}, {value}, options)"
        : $"{G}Write<{member.TypeName}>({value}, options)";

    private static string ReadExpr(MemberModel member, int index, string term) =>
        member.AsAtom ? $"{G}ReadAtomString({term}, options)"
        : member.ConverterTypeName is not null ? $"{G}ReadVia(_conv{index}, {term}, options)"
        : $"{G}Read<{member.TypeName}>({term}, options)";

    private static string ShortName(string fullyQualified)
    {
        var name = fullyQualified.Replace("global::", string.Empty);
        var dot = name.LastIndexOf('.');
        return dot < 0 ? name : name.Substring(dot + 1);
    }

    private static string Quote(string value) =>
        "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
